apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  ingressClassName: nginx
  rules:
  - host: sockshop.paulskay.me
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: front-end
              port:
                number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: carts
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: catalogue
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: orders
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: payment
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: queue-master
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: rabbitmq
        #       port:
        #         number: 5672
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: rabbitmq
        #       port:
        #         number: 9090
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: shipping
        #       port:
        #         number: 80
        # - path: "/"
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: user
        #       port:
        #         number: 80